// ═══════════════════════════════════════════════════════════
// BEGGAR NETWORK — Mascot + Helpers (no fake/sample data — real data is Supabase-backed)
// ═══════════════════════════════════════════════════════════

// ── Pixel mascot ──────────────────────────────────────────
window.BEGGAR_KING_GRID = `
................
....C...C.......
...CC..CCC......
..CCCCCCCCC.....
..cccccccccc....
...SSSSSSSS.....
..SSSSSSSSSS....
.SSSSSSSSSSSS...
.SSEsSSSSEsS....
.SSSSSSSSSSSS...
.SSSSSSSSSSSS...
.SSSsssssssSS...
..SSSHHHHHSS....
...SSSSSSSS.....
....BBBBBB......
...BBBBBBBB.....
..BBBbBBBBBB....
..BBBbBOBBBB....
...BBBBBBBB.....
....BBBBBB......
`.trim();

window.MASCOT_PALETTE = {
  'K': '#0F0E0B', 'B': '#2B231C', 'b': '#44382B',
  'S': '#DAB78A', 's': '#B0916A',
  'C': '#E8A02C', 'c': '#B26A12',
  'O': '#FF6B35',
  'H': '#0F0E0B', 'E': '#0F0E0B', 'W': '#FFFFFF',
};

window.renderMascot = function(scale = 2, opts = {}) {
  const grid = window.BEGGAR_KING_GRID;
  const rows = grid.split('\n');
  const h = rows.length;
  const w = Math.max(...rows.map(r => r.length));
  const W = w * scale, H = h * scale;
  let rects = '';
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < rows[y].length; x++) {
      const ch = rows[y][x];
      if (ch === '.' || ch === ' ') continue;
      const color = window.MASCOT_PALETTE[ch] || '#FF00FF';
      rects += `<rect x="${x}" y="${y}" width="1.02" height="1.02" fill="${color}"/>`;
    }
  }
  const cls = opts.className ? ` class="${opts.className}"` : '';
  return `<svg${cls} width="${W}" height="${H}" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges" xmlns="http://www.w3.org/2000/svg" style="display:inline-block;vertical-align:middle">${rects}</svg>`;
};

// ── Helpers (CAT_EMOJI and getGrade live in config.js; real spot data
// and leaderboard come from Supabase — see js/map.js loadData() and
// sql/verifications.sql. The fabricated window.SPOTS / window.LEADERBOARD
// demo arrays that used to live here were unused dead code and removed
// before the public release (2026-07-04). ──

window.formatPrice = function(p) {
  if (p % 1 === 0) return '$' + p;
  return '$' + p.toFixed(2);
};
